"""
bianchi9_test.py -- first numerics on the system in bianchi9_system.pkl (via bianchi9_rhs.py)

  (i)  Einstein-manifold trajectory: start on GR data, integrate the FULL quadratic-gravity
       flow, confirm it stays on the manifold (delta = 0 to roundoff), the constraint is
       conserved, and the mixmaster bounces appear.
  (ii) Transverse linearisation: integrate the tangent vector along the same trajectory with
       the analytic Jacobian; the transverse part delta_v = v_hi - (d gr/d y_lo) v_lo measures
       growth of the Weyl ghost off the manifold.  Renormalised log growth G(tau) is saved
       against alpha, together with the bounce record.

Time: dt = e^{3 alpha} d tau  (Misner-type lapse, bounces roughly equispaced in tau; the pkl
equations are in proper time and are simply rescaled).  Control parameter: H/M = alpha'/M.

Run:   %run bianchi9_test.py --M 1 --alpha-end -6
"""
import sys, time, pickle, argparse
import numpy as np
from scipy.integrate import solve_ivp

p = argparse.ArgumentParser()
p.add_argument('--M', type=float, default=1.0)
p.add_argument('--alpha0', type=float, default=0.0)
p.add_argument('--alpha-end', type=float, default=-6.0)
p.add_argument('--HM-max', type=float, default=3.0, help='stop when H/M exceeds this')
p.add_argument('--theta', type=float, default=np.pi, help='initial Kasner angle in the beta-plane (pi: into the beta_+ -> -inf wall)')
p.add_argument('--beta0', type=float, default=0.0, help='initial beta_+')
p.add_argument('--rtol', type=float, default=1e-11)
p.add_argument('--out', default='test_run.npz')
p.add_argument('--seed-off', type=float, default=0.0, help='initial |delta| off the manifold (nonlinear test)')
args = p.parse_args()

t0 = time.time()
import bianchi9_rhs as m           # generated by bianchi9_codegen.py
f_rhs, f_jac, f_gr, f_grj, f_con, f_conGR, f_dconGR = m.rhs, m.jac, m.gr, m.grj, m.con, m.conGR, m.dconGR
print(f"[{time.time()-t0:5.1f}s] bianchi9_rhs imported", flush=True)

Mv = args.M

def gr_initial(alpha0, theta, beta0=0.0):
    """GR data: alpha, beta = 0, beta' along angle theta, alpha' from the GR constraint."""
    y = np.zeros(10)
    y[0] = alpha0; y[2] = beta0
    # Kasner-like: alpha'^2 = beta'^2 + potential; pick |beta'| = 1 in these units
    y[4], y[5] = np.cos(theta), np.sin(theta)
    y[1] = -1.0                                   # collapsing branch, Newton for the constraint
    for _ in range(100):
        c = f_conGR(y, Mv); d = f_dconGR(y, Mv)
        y[1] -= c / d
        if abs(c) < 1e-15: break
    y[6:] = f_gr(y, Mv)
    return y

def delta(y):
    g = np.asarray(f_gr(y, Mv))
    return (y[6:] - g) / (1 + np.abs(g).max())      # relative: beta''' grows like e^{-9 alpha}

def delta_v(y, v):
    """transverse part of the tangent vector (proper-time units)"""
    return v[6:] - np.asarray(f_grj(y, Mv)) @ v[:6]

def ghost_action(y, dv):
    """adiabatic action of a heavy ghost oscillation, up to a constant. For
    delta beta = A cos(M t): delta beta'' ~ M^2 A, delta beta''' ~ M^3 A, J ~ e^{3 alpha} M A^2,
    so J ~ e^{3 alpha} (d2^2 + d3^2 / M^2) / M^3. Constant along a Kasner epoch if H << M."""
    return np.exp(3 * y[0]) * (dv[0]**2 + dv[1]**2 + (dv[2]**2 + dv[3]**2) / Mv**2) / Mv**3

# ------------------------------------------------------------ combined ODE in tau
def F(tau, Y):
    y, v = Y[:10], Y[10:]
    N = np.exp(3 * y[0])
    fy = np.asarray(f_rhs(y, Mv))
    J = np.asarray(f_jac(y, Mv))
    # d/dtau (N f) acting on v:  N J v + f (dN/dy . v),  dN/dy = 3 N e_alpha
    dv = N * (J @ v) + fy * (3 * N * v[0])
    return np.concatenate([N * fy, dv])

y0 = gr_initial(args.alpha0, args.theta, args.beta0)
if args.seed_off:
    y0[6:8] += args.seed_off
rng = np.random.default_rng(0)
v0 = rng.normal(size=10); v0 /= np.linalg.norm(v0)
print(f"   initial H/M = {abs(y0[1])/Mv:.3f}, |delta0| = {np.linalg.norm(delta(y0)):.1e}, "
      f"constraint = {f_con(y0, Mv):.1e}")

# integrate in chunks, renormalising v; stop when alpha reaches alpha_end
taus, alphas, Hs, dnorm, cons, G, Gpar = [], [], [], [], [], [], []
bp_rec, bm_rec = [], []
Y = np.concatenate([y0, v0]); tau = 0.0; logG = 0.0
dtau = 0.05
stop = lambda tau, Y: Y[0] - args.alpha_end
stop.terminal = True
while True:
    sol = solve_ivp(F, (tau, tau + dtau), Y, method='DOP853', rtol=args.rtol, atol=1e-14,
                    events=stop, dense_output=False, max_step=0.05)
    Y = sol.y[:, -1]; tau = sol.t[-1]
    y, v = Y[:10], Y[10:]
    dv = delta_v(y, v)
    nv = np.linalg.norm(v)
    taus.append(tau); alphas.append(y[0]); Hs.append(abs(y[1]) / Mv)
    dnorm.append(np.linalg.norm(delta(y))); cons.append(f_con(y, Mv))
    G.append(logG + 0.5 * np.log(ghost_action(y, dv)))   # log sqrt(ghost action) of the tangent vector
    Gpar.append(logG + np.log(np.linalg.norm(v[:6] * np.array([1, np.exp(3*y[0]), 1, 1, np.exp(3*y[0]), np.exp(3*y[0])]))))
    bp_rec.append(y[2]); bm_rec.append(y[3])
    logG += np.log(nv); Y[10:] = v / nv
    if len(taus) % 20 == 0:
        print(f"   tau={tau:6.2f} alpha={y[0]:7.3f} H/M={Hs[-1]:.3f} steps={len(sol.t)} G={G[-1]:+.2f} Gpar={Gpar[-1]:+.2f} ({time.time()-t0:.0f}s)", flush=True)
    if sol.status == 1 or not np.isfinite(y).all() or Hs[-1] > args.HM_max:
        break
    if time.time() - t0 > 600:
        print("   time limit"); break

taus, alphas, Hs, dnorm, cons, G, Gpar = map(np.array, (taus, alphas, Hs, dnorm, cons, G, Gpar))
print(f"[{time.time()-t0:5.1f}s] done: tau = {taus[-1]:.2f}, alpha {alphas[0]:.2f} -> {alphas[-1]:.2f}, "
      f"H/M {Hs[0]:.3f} -> {Hs[-1]:.3f}")
print(f"   max rel |delta| on manifold: {dnorm.max():.2e}   (invariance)")
print(f"   max |constraint|         : {np.abs(cons).max():.2e}   (conservation)")
# bounces: sign changes of the Kasner direction -> count turning points of |beta|
beta = np.hypot(np.array(bp_rec), np.array(bm_rec))
turns = np.sum(np.diff(np.sign(np.diff(beta))) != 0)
print(f"   bounces (turning points of |beta|): {turns}")
print(f"   log-growth over d alpha = {alphas[-1]-alphas[0]:.2f}:  transverse {G[-1]-G[0]:+.2f}   on-manifold {Gpar[-1]-Gpar[0]:+.2f}")
np.savez(args.out, tau=taus, alpha=alphas, HM=Hs, delta=dnorm, con=cons, G=G, Gpar=Gpar,
         bp=np.array(bp_rec), bm=np.array(bm_rec), M=Mv)
print(f"   wrote {args.out}")
