"""
bianchi9_codegen.py -- turn bianchi9_system.pkl into a plain numpy module bianchi9_rhs.py

Functions written (all take y[10] and M):
    rhs(y, M)   -> ydot[10]        proper-time flow
    jac(y, M)   -> J[10,10]        d ydot / d y
    gr(y, M)    -> [bp2, bm2, bp3, bm3]_GR      Einstein-manifold values from y[:6]
    grj(y, M)   -> d gr / d y[:6]  [4,6]
    con(y, M)   -> Hamiltonian constraint (alpha'' eliminated)
    conGR(y, M), dconGR(y, M) -> GR constraint and its alpha' derivative (for initial data)
Common subexpressions are eliminated once, per function group; the generated file is flat
Python with math.exp / math.sqrt, fast for scalar calls (what an ODE integrator makes).

Run:  %run bianchi9_codegen.py      (a few minutes, once)
"""
import pickle, time
import sympy as sp
from sympy.printing.pycode import pycode

t0 = time.time()
S = pickle.load(open('bianchi9_system.pkl', 'rb'))
state = sp.symbols(S['state'])
M = sp.Symbol(S['M'], positive=True)
al0, al1, bp0, bm0, bp1, bm1, bp2, bm2, bp3, bm3 = state

rhs = sp.Matrix([al1, S['al2'], bp1, bm1, bp2, bm2, bp3, bm3, S['b4'][0], S['b4'][1]])
gr = sp.Matrix(S['gr_b2'] + S['gr_b3'])
con = S['Con'].subs(sp.Symbol('al2'), S['al2'])
conGR = S['Con_GR']

def emit(name, exprs, shape, out):
    """exprs: flat list of sympy expressions -> python function returning array of shape."""
    t1 = time.time()
    reps, red = sp.cse(exprs, optimizations='basic')
    lines = [f"def {name}(y, M):",
             "    al0, al1, bp0, bm0, bp1, bm1, bp2, bm2, bp3, bm3 = y"]
    for s_, e in reps:
        lines.append(f"    {s_} = {pycode(e)}")
    body = ", ".join(pycode(e) for e in red)
    if shape is None:
        lines.append(f"    return {body}")
    else:
        lines.append(f"    return np.array([{body}]).reshape({shape})")
    out.append("\n".join(lines) + "\n\n")
    print(f"[{time.time()-t0:6.1f}s] {name}: {len(reps)} subexpressions ({time.time()-t1:.0f}s)", flush=True)

# Pieces of the fourth-order solve, recomputed from the Lagrangian pieces stored in the pkl:
# E_alpha = c1 al2 + c0 ;  al3 = n3 / c1^3 ;  A b4 = r  (A, r already multiplied by c1^3).
# Re-derive them here from L exactly as bianchi9_derive.py does (cheap, < 20 s).
L = S['L']; KMAX = 6
J = {nm: [sp.Symbol(f'{nm}{k}') for k in range(KMAX + 1)] for nm in ('al', 'bp', 'bm', 'N')}
def D(expr):
    return sum(sp.diff(expr, J[nm][k]) * J[nm][k+1] for nm in J for k in range(KMAX))
def EL(Lx, nm, order=4):
    outx = sp.S(0)
    for k in range(order + 1):
        term = sp.diff(Lx, J[nm][k])
        for _ in range(k): term = D(term)
        outx += (-1)**k * term
    return sp.expand(outx)
gauge = {J['N'][0]: 1, J['N'][1]: 0, J['N'][2]: 0, J['N'][3]: 0}
E_al = EL(L, 'al').subs(gauge); E_bp = EL(L, 'bp').subs(gauge); E_bm = EL(L, 'bm').subs(gauge)
c1 = E_al.coeff(J['al'][2]); c0 = sp.expand(E_al - c1 * J['al'][2])
n3 = sp.expand(-(D(c0) * c1 - c0 * D(c1)))
n3 = sp.expand(n3.subs(J['al'][2], -c0 / c1) * c1)
def clear(E):
    E = sp.expand(E); outx = sp.S(0)
    for term in sp.Add.make_args(E):
        p2 = sp.degree(term, J['al'][2]); p3 = sp.degree(term, J['al'][3])
        base = term / J['al'][2]**p2 / J['al'][3]**p3
        outx += base * (-c0)**p2 * c1**(3 - p2 - 3*p3) * n3**p3
    return sp.expand(outx)
Eb = [clear(E) for E in (E_bp, E_bm)]
Amat, rvec = sp.linear_eq_to_matrix(Eb, [J['bp'][4], J['bm'][4]])
print(f"[{time.time()-t0:6.1f}s] pieces rebuilt")
# sanity: the pieces reproduce the stored closed-form solution
import random; random.seed(2)
pt = {s_: random.uniform(-.5, .5) for s_ in state}; pt[M] = 1.1
b4num = Amat.subs(pt).LUsolve(rvec.subs(pt))
print("   pieces vs stored b4:", max(abs(sp.N(b4num[i] - S['b4'][i].subs(pt))) for i in range(2)))

out = ["# generated by bianchi9_codegen.py from bianchi9_system.pkl -- do not edit\n",
       "import numpy as np\nfrom math import exp, sqrt\n\n"]
emit('pieces', [c0, c1, Amat[0,0], Amat[0,1], Amat[1,0], Amat[1,1], rvec[0], rvec[1]], None, out)
out.append('''def rhs(y, M):
    c0, c1, a11, a12, a21, a22, r1, r2 = pieces(y, M)
    det = a11*a22 - a12*a21
    return np.array([y[1], -c0/c1, y[4], y[5], y[6], y[7], y[8], y[9],
                     (a22*r1 - a12*r2)/det, (a11*r2 - a21*r1)/det])

def jac(y, M, h=1e-6):
    """central-difference Jacobian; rows 0,2..7 are exact"""
    Jm = np.zeros((10, 10))
    Jm[0, 1] = Jm[2, 4] = Jm[3, 5] = Jm[4, 6] = Jm[5, 7] = Jm[6, 8] = Jm[7, 9] = 1.0
    for i in range(10):
        e = np.zeros(10); e[i] = h * (1 + abs(y[i]))
        fp = rhs(y + e, M); fm = rhs(y - e, M)
        Jm[1, i] = (fp[1] - fm[1]) / (2*e[i]); Jm[8:, i] = (fp[8:] - fm[8:]) / (2*e[i])
    return Jm

''')
emit('gr', list(gr), (4,), out)
emit('grj', list(gr.jacobian(sp.Matrix(state[:6]))), (4, 6), out)
emit('con', [con], None, out)
emit('conGR', [conGR], None, out)
emit('dconGR', [sp.diff(conGR, al1)], None, out)
src = "".join(out).replace("math.exp", "exp").replace("math.sqrt", "sqrt")
open('bianchi9_rhs.py', 'w').write(src)
print(f"[{time.time()-t0:6.1f}s] wrote bianchi9_rhs.py ({len(src)//1000} kB)")

# self-check against direct lambdify at a random point
import numpy as np, importlib, random
m = importlib.import_module('bianchi9_rhs')
random.seed(0)
y = np.array([random.uniform(-.5, .5) for _ in range(10)]); Mv = 1.3
f = sp.lambdify([state, M], list(rhs), 'numpy', cse=True)
print("   rhs check vs lambdify:", np.abs(m.rhs(y, Mv) - np.array(f(y, Mv))).max())
J = m.jac(y, Mv); h = 1e-6
Jfd = np.array([(m.rhs(y + h*np.eye(10)[i], Mv) - m.rhs(y - h*np.eye(10)[i], Mv)) / (2*h) for i in range(10)]).T
print("   jac (fd) self-consistency:", np.abs(J - Jfd).max() / (1 + np.abs(J).max()))
Gj = m.grj(y, Mv)
Gfd = np.array([(m.gr(y + h*np.eye(10)[i], Mv) - m.gr(y - h*np.eye(10)[i], Mv)) / (2*h) for i in range(6)]).T
print("   grj check vs finite difference:", np.abs(Gj - Gfd).max() / (1 + np.abs(Gj).max()))
