"""
bianchi9_symp.py -- Ostrogradsky canonical map and symplectic form for the system in
bianchi9_system.pkl, emitted as plain numpy code into bianchi9_symp_gen.py.

Canonical coordinates (N = 1):
    z = (alpha, bp, bm, bp1, bm1 | p_alpha, P1p, P1m, P2p, P2m)
    p_alpha = dL/d alpha'
    P2      = dL/d beta''
    P1      = dL/d beta' - d/dt P2
Omega_can = [[0, I5], [-I5, 0]];  Omega_y(y) = (dz/dy)^T Omega_can (dz/dy)  (10x10, antisymmetric)
in the integrator coordinates y = (al0, al1, bp0, bm0, bp1, bm1, bp2, bm2, bp3, bm3).

P1 contains alpha'' through dP2/dt; it is replaced by its on-shell value al2(y), so z(y) are the
canonical coordinates of the solution through y and the pulled-back form is still invariant
under the linearised flow (checked numerically below).

Run:  %run bianchi9_symp.py      (~30 s)
"""
import pickle, time
import sympy as sp
from sympy.printing.pycode import pycode

t0 = time.time()
S = pickle.load(open('bianchi9_system.pkl', 'rb'))
state = sp.symbols(S['state'])
M = sp.Symbol(S['M'], positive=True)
al0, al1, bp0, bm0, bp1, bm1, bp2, bm2, bp3, bm3 = state
KMAX = 6
J = {nm: [sp.Symbol(f'{nm}{k}') for k in range(KMAX + 1)] for nm in ('al', 'bp', 'bm', 'N')}
def D(expr):
    return sum(sp.diff(expr, J[nm][k]) * J[nm][k+1] for nm in J for k in range(KMAX))

gauge = {J['N'][0]: 1, J['N'][1]: 0, J['N'][2]: 0, J['N'][3]: 0}
L = S['L'].subs(gauge)
p_al = sp.expand(sp.diff(L, al1))
P2p = sp.expand(sp.diff(L, bp2)); P2m = sp.expand(sp.diff(L, bm2))
al2 = sp.Symbol('al2')
P1p = sp.expand(sp.diff(L, bp1) - D(P2p)).subs(al2, S['al2'])   # on-shell alpha''
P1m = sp.expand(sp.diff(L, bm1) - D(P2m)).subs(al2, S['al2'])
for nm, e in (('p_alpha', p_al), ('P1p', P1p), ('P1m', P1m), ('P2p', P2p), ('P2m', P2m)):
    bad = [s_ for s_ in e.free_symbols if s_ not in state and s_ != M]
    assert not bad, (nm, bad)
print("   P2+ =", sp.factor(P2p))
print("   p_alpha =", sp.factor(p_al))
z = sp.Matrix([al0, bp0, bm0, bp1, bm1, p_al, P1p, P1m, P2p, P2m])
dz = z.jacobian(sp.Matrix(state))
print(f"[{time.time()-t0:5.1f}s] canonical map built")

# emit
def emit(name, exprs, shape, out):
    reps, red = sp.cse(exprs, optimizations='basic')
    lines = [f"def {name}(y, M):", "    al0, al1, bp0, bm0, bp1, bm1, bp2, bm2, bp3, bm3 = y"]
    for s_, e in reps:
        lines.append(f"    {s_} = {pycode(e)}")
    body = ", ".join(pycode(e) for e in red)
    lines.append(f"    return np.array([{body}]).reshape({shape})")
    out.append("\n".join(lines) + "\n\n")
out = ["# generated by bianchi9_symp.py -- do not edit\nimport numpy as np\nfrom math import exp, sqrt\n\n"]
emit('z', list(z), (10,), out)
emit('dz', list(dz), (10, 10), out)
out.append('''OMEGA_CAN = np.block([[np.zeros((5, 5)), np.eye(5)], [-np.eye(5), np.zeros((5, 5))]])

def omega(y, M):
    """symplectic form in y-coordinates: Omega_y = dz^T Omega_can dz"""
    d = dz(y, M)
    return d.T @ OMEGA_CAN @ d
''')
src = "".join(out).replace("math.exp", "exp").replace("math.sqrt", "sqrt")
open('bianchi9_symp_gen.py', 'w').write(src)
print(f"[{time.time()-t0:5.1f}s] wrote bianchi9_symp_gen.py ({len(src)//1000} kB)")

# numerical checks
import numpy as np, importlib, random
g = importlib.import_module('bianchi9_symp_gen')
m = importlib.import_module('bianchi9_rhs')
random.seed(0)
y = np.array([random.uniform(-.5, .5) for _ in range(10)]); Mv = 1.3
d = g.dz(y, Mv)
print("   |det dz/dy| =", abs(np.linalg.det(d)))
# dz vs finite difference
h = 1e-6
dfd = np.array([(g.z(y + h*np.eye(10)[i], Mv) - g.z(y - h*np.eye(10)[i], Mv)) / (2*h) for i in range(10)]).T
print("   dz check vs finite difference:", np.abs(d - dfd).max() / (1 + np.abs(d).max()))
# Hamiltonian check: the flow is Hamiltonian w.r.t. Omega_y with H = constraint?  Weaker but
# decisive test: the linearised flow preserves Omega_y:  d/dt Omega_y(v1, v2) = 0, i.e.
# (J^T Om + Om J + dOm/dt) = 0 with dOm/dt = sum_k dOm/dy_k f_k.
Jm = m.jac(y, Mv); f = m.rhs(y, Mv); Om = g.omega(y, Mv)
dOm = sum(((g.omega(y + h*np.eye(10)[k], Mv) - g.omega(y - h*np.eye(10)[k], Mv)) / (2*h)) * f[k] for k in range(10))
res = Jm.T @ Om + Om @ Jm + dOm
print("   symplectic-form conservation residual:", np.abs(res).max() / np.abs(Om).max())
